### PR TITLE
Implement --run-until

### PR DESCRIPTION
**Pull request by kdm9**
See #114 

Work in progress

### CODE REVIEW

**Comment by kdm9** [comment]
@fenderglass is there a nice test dataset you use so I can test this on something small?

**Comment by mikolmogorov** [comment]
Sure, use one of those from here: https://github.com/fenderglass/Flye/blob/flye/docs/USAGE.md#examples

**Comment by mikolmogorov** [comment]
Just checking in - are you still working on the update or it is ready for testing?

**Comment by kdm9** [comment]
It's ready for testing thanks Mikhail!

**Comment by mikolmogorov** [comment]
Merged, thanks!

**Comment by mikolmogorov** [comment]
Renamed it to `--stop-after` though - so it's less ambiguous if the last stage is inclusive or not.

**Pull request merged**
