### PR TITLE
Replace std::unordered_map and std::unordered_set

### PR DESCRIPTION
**Pull request by dnbaker**
with faster and more memory efficient hashmaps (ska::flat_hash_{map,set}).

### CODE REVIEW

**Comment by mikolmogorov** [comment]
Thank you. Can you provide benchmarks showing the improvements? If the performance / memory changes are minimal - I would prefer to keep the original hash maps for stability.

**Comment by dnbaker** [comment]
I've found unordered_map to be shockingly slow (~factor of 10) in applications where it's been a core data structure, so I expect it will make a substantial difference considering how much it's used but I'm waiting for a benchmark between these two versions to complete and will let you know.

**Comment by dnbaker** [comment]
On an Arabica dataset and the same command-line, but with different executables (`time -v bin/flye-assemble -t50 -l log ../ERR2173373.fastq.gz output.assembly 130000000 ../db/Flye/sample.cfg`):

Master:
```
[2019-03-05 15:22:15] INFO: Reading sequences
[2019-03-05 15:23:16] INFO: Generating solid k-mer index
[2019-03-05 15:29:29] INFO: Counting kmers (1/2):
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-03-05 15:29:57] INFO: Counting kmers (2/2):
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-03-05 15:32:16] INFO: Filling index table
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-03-05 15:35:30] INFO: Extending reads
[2019-03-05 15:39:52] INFO: Overlap-based coverage: 17
[2019-03-05 15:39:52] INFO: Median overlap divergence: 0.158101
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-03-05 16:10:22] INFO: Assembled 1049 draft contigs
[2019-03-05 16:10:27] INFO: Generating contig sequences
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
	Command being timed: "bin/flye-assemble -t50 -l log ../ERR2173373.fastq.gz output.assembly 130000000 ../db/Flye/zomg.cfg"
	User time (seconds): 112019.61
	System time (seconds): 2213.89
	Percent of CPU this job got: 3631%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 52:25.82
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 34180572
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 731230156
	Voluntary context switches: 297983
	Involuntary context switches: 337095
	Swaps: 0
	File system inputs: 0
	File system outputs: 334648
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

ska::flat_hash_{set,map}:

```
[2019-03-05 15:12:05] INFO: Reading sequences
[2019-03-05 15:13:02] INFO: Generating solid k-mer index
[2019-03-05 15:18:01] INFO: Counting kmers (1/2):
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-03-05 15:18:18] INFO: Counting kmers (2/2):
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-03-05 15:19:33] INFO: Filling index table
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-03-05 15:21:29] INFO: Extending reads
[2019-03-05 15:24:24] INFO: Overlap-based coverage: 17
[2019-03-05 15:24:24] INFO: Median overlap divergence: 0.158101
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-03-05 15:53:34] INFO: Assembled 1053 draft contigs
[2019-03-05 15:53:36] INFO: Generating contig sequences
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
	Command being timed: "bin/flye-assemble -t50 -l log ../../ERR2173373.fastq.gz output.assembly 130000000 zomg.cfg"
	User time (seconds): 108922.07
	System time (seconds): 780.84
	Percent of CPU this job got: 3893%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 46:57.33
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 34986420
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 100903156
	Voluntary context switches: 128480
	Involuntary context switches: 302991
	Swaps: 0
	File system inputs: 0
	File system outputs: 334896
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

So it seems to have a benefit of a total runtime speedup of ~11%. The output is byte-for-byte identical.

**Comment by mikolmogorov** [comment]
This seems counter-intuitive, because most of the difference in time comes from the index building stage, but unordered maps/sets are not used there. Also, if you consider CPU user time, there is only ~2% difference, and there is more difference in system time (the first run generated more page faults). Did you do these run in parallel? For a fair comparison, I would run them one by one and make sure there are no other processes interfering.

**Comment by dnbaker** [comment]
I re-ran this 10 times per version. The runtimes did not pass a t-test, so I'm inclined to believe there's no reason to make this change.

Thanks for your contribution!

**Comment by mikolmogorov** [comment]
Thank you - appreciate you took time to run these tests.

**Pull request closed without merging**
