### PR TITLE
Refactoring and packaging

### PR DESCRIPTION
**Pull request by druvus**
Hi, 
we have refactored the code a little bit to avoid setting system paths. In addition the proposed changes makes it easier to pack the code into a python package using the added setup script which would simplify installation. Some of the documentation should be updated but I could make a second PR in case you accept those changes.

### CODE REVIEW

**Comment by fenderglass** [comment]
Hi,
Thank you! I'll take a look shortly.

**Comment by fenderglass** [comment]
Hi,

Thank you for your contribution! I think this is a useful way to integrate the program with Python packaging system and make it easily installable into OS. I will be happy to approve this, but I would also require a couple of changes before that:

1. Most importantly, there should be a possibility for users to run ABruijn without any installation from the repository folder. I know, that one can run 'setup.py install --user', but even that may cause troubles in some configurations. To achieve that, I would keep 'abruijn.py' script in the root folder, with referencing it from 'setup.py'. I would also keep the original separation of 'main.py' file (it logically belongs to the package code) and a driver script (which could be installable). There might be a conflict between 'local' and 'package' implementation of the driver script ('local' version should add binaries to the executable path) - do you think, it is possible to unify them?

2. Is there a way to integrate building c++ binaries via Make with the 'setup.py' script more tightly? That is, I would like to see 'make' command triggered during the package build phase, but not at any 'setup.py' invocation ('python setup.py help', for example, should not trigger 'make')

3. I would keep checking of Python interpreter version - 2.7 is a requirement, 3.x support is currently not guaranteed (most likely, it won't work now).

**Comment by fenderglass** [comment]
Also, I think it is a good idea to add bootstrapped version of setuptools into the package, as it is not the part of standard library: https://pypi.python.org/pypi/ez_setup

**Comment by druvus** [comment]
Hi, 
thanks for your positive response! I will take a look at your suggestions together with @emilhaegglund. At least point 2 and 3 should be quite feasible to fix but probably also the first one.

**Comment by fenderglass** [comment]
Hi,

I think I have figured out how to easily resolve these issues. Unless you are in the middle of something, I can proceed with merging your pull request and making the highlighted fixes - would be that ok? I am planning to include this into the upcoming release.

**Comment by druvus** [comment]
Sounds good.

**Pull request merged**
